# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CsvImportResponse(BaseModel):
    """
    CsvImportResponse
    """ # noqa: E501
    task_id: Optional[StrictStr] = None
    timestamp_ms: Optional[StrictInt] = None
    agent_instructions: Optional[StrictStr] = None
    usage: Optional[StrictStr] = None
    message: Optional[StrictStr] = None
    list_id: StrictStr = Field(description="Identifier of the list the CSV was imported into.")
    rows_parsed: StrictInt = Field(description="Total data rows read from the CSV (excludes the header).")
    rows_imported: StrictInt = Field(description="Rows that landed as importable contacts.")
    rows_skipped: StrictInt = Field(description="Rows dropped during parsing (see skip_reasons).")
    skip_reasons: Optional[Dict[str, Optional[StrictInt]]] = Field(default=None, description="Skip counts by stable reason key (missing_required, duplicate_email, duplicate_linkedin, row_cap_exceeded).")
    sample_skip_rows: Optional[List[Optional[StrictInt]]] = Field(default=None, description="Up to 10 1-indexed row numbers (header is row 1) that were skipped, for spot-checking the file.")
    workflow_id: Optional[StrictStr] = None
    enrichment_status_url: Optional[StrictStr] = None
    idempotency_replayed: Optional[StrictBool] = Field(default=False, description="True when served from the idempotency cache — the CSV was NOT re-imported and NO credits were re-charged.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["task_id", "timestamp_ms", "agent_instructions", "usage", "message", "list_id", "rows_parsed", "rows_imported", "rows_skipped", "skip_reasons", "sample_skip_rows", "workflow_id", "enrichment_status_url", "idempotency_replayed"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CsvImportResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict['task_id'] = None

        # set to None if timestamp_ms (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_ms is None and "timestamp_ms" in self.model_fields_set:
            _dict['timestamp_ms'] = None

        # set to None if agent_instructions (nullable) is None
        # and model_fields_set contains the field
        if self.agent_instructions is None and "agent_instructions" in self.model_fields_set:
            _dict['agent_instructions'] = None

        # set to None if usage (nullable) is None
        # and model_fields_set contains the field
        if self.usage is None and "usage" in self.model_fields_set:
            _dict['usage'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if workflow_id (nullable) is None
        # and model_fields_set contains the field
        if self.workflow_id is None and "workflow_id" in self.model_fields_set:
            _dict['workflow_id'] = None

        # set to None if enrichment_status_url (nullable) is None
        # and model_fields_set contains the field
        if self.enrichment_status_url is None and "enrichment_status_url" in self.model_fields_set:
            _dict['enrichment_status_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CsvImportResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_id": obj.get("task_id"),
            "timestamp_ms": obj.get("timestamp_ms"),
            "agent_instructions": obj.get("agent_instructions"),
            "usage": obj.get("usage"),
            "message": obj.get("message"),
            "list_id": obj.get("list_id"),
            "rows_parsed": obj.get("rows_parsed"),
            "rows_imported": obj.get("rows_imported"),
            "rows_skipped": obj.get("rows_skipped"),
            "skip_reasons": obj.get("skip_reasons"),
            "sample_skip_rows": obj.get("sample_skip_rows"),
            "workflow_id": obj.get("workflow_id"),
            "enrichment_status_url": obj.get("enrichment_status_url"),
            "idempotency_replayed": obj.get("idempotency_replayed") if obj.get("idempotency_replayed") is not None else False
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


