# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class EstimateCostResponse(BaseModel):
    """
    EstimateCostResponse
    """ # noqa: E501
    quote_id: StrictStr = Field(description="HMAC-signed quote handle (`qte_<kid>_<issued_at>_<sig>`) that the paired paid tool must present at execution time. Single-use and bound to the canonical request (tool, list/filters, scope, row_count, org).")
    expires_at: StrictInt = Field(description="Unix epoch SECONDS at which the quote expires (issue time + `CLEANLIST_QUOTE_TTL_SECONDS`, 5 min default). Re-estimate after this to obtain a fresh quote.")
    estimated_cost: StrictInt = Field(description="Credits this operation will cost — the authoritative signed spend cap. Execution rejects (`spend_cap_exceeded`) if the recomputed cost would exceed it.")
    tool: StrictStr = Field(description="Echo of the priced tool.")
    row_count: StrictInt = Field(description="Number of rows/entities the estimate priced — derived from the list or cohort when applicable, not the caller's raw input.")
    filter_hash: StrictStr = Field(description="Stable digest of the canonical filter/list/cohort shape bound into the quote signature; `none` when there is no filter object.")
    available_credits: StrictInt = Field(description="The organization's current credit balance at estimate time.")
    sufficient: StrictBool = Field(description="True when `available_credits >= estimated_cost`. False signals the org must top up at billing before the operation can run.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["quote_id", "expires_at", "estimated_cost", "tool", "row_count", "filter_hash", "available_credits", "sufficient"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EstimateCostResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EstimateCostResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "quote_id": obj.get("quote_id"),
            "expires_at": obj.get("expires_at"),
            "estimated_cost": obj.get("estimated_cost"),
            "tool": obj.get("tool"),
            "row_count": obj.get("row_count"),
            "filter_hash": obj.get("filter_hash"),
            "available_credits": obj.get("available_credits"),
            "sufficient": obj.get("sufficient")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


