# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ExportCsvResponse(BaseModel):
    """
    ExportCsvResponse
    """ # noqa: E501
    list_id: StrictStr = Field(description="ID of the Lead List that was exported.")
    download_url: StrictStr = Field(description="Time-limited, SAS-signed URL to download the generated CSV file. The signature (`sig`) and expiry (`exp`) query params gate access; the link stops working after `expires_at`.")
    expires_at: StrictStr = Field(description="ISO-8601 UTC timestamp at which `download_url` expires. Generated URLs are valid for 24 hours.")
    row_count: StrictInt = Field(description="Number of data rows written to the CSV (excludes the header row).")
    file_size_bytes: StrictInt = Field(description="Size of the generated CSV file in bytes.")
    __properties: ClassVar[List[str]] = ["list_id", "download_url", "expires_at", "row_count", "file_size_bytes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExportCsvResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExportCsvResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "list_id": obj.get("list_id"),
            "download_url": obj.get("download_url"),
            "expires_at": obj.get("expires_at"),
            "row_count": obj.get("row_count"),
            "file_size_bytes": obj.get("file_size_bytes")
        })
        return _obj


