# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SmartAgentRun(BaseModel):
    """
    SmartAgentRun
    """ # noqa: E501
    task_id: StrictStr = Field(description="Run id for this smart-agent run — poll it via GET /smart-agents/{id}.")
    list_id: StrictStr = Field(description="UUID of the lead list this run targeted.")
    column_name: StrictStr = Field(description="Name of the column the run wrote its output to.")
    agent_type: StrictStr = Field(description="Agent / smart-column type the run executed as (e.g. `custom_ai`, `cold_intro_email`).")
    status: StrictStr = Field(description="Lifecycle state: `pending`, `processing`, `completed`, or `failed`.")
    total: Optional[StrictInt] = Field(default=0, description="Total leads scheduled for this run.")
    processed: Optional[StrictInt] = Field(default=0, description="Leads processed so far (succeeded + failed).")
    failed: Optional[StrictInt] = Field(default=0, description="Leads that errored during processing.")
    created_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["task_id", "list_id", "column_name", "agent_type", "status", "total", "processed", "failed", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SmartAgentRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SmartAgentRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_id": obj.get("task_id"),
            "list_id": obj.get("list_id"),
            "column_name": obj.get("column_name"),
            "agent_type": obj.get("agent_type"),
            "status": obj.get("status"),
            "total": obj.get("total") if obj.get("total") is not None else 0,
            "processed": obj.get("processed") if obj.get("processed") is not None else 0,
            "failed": obj.get("failed") if obj.get("failed") is not None else 0,
            "created_at": obj.get("created_at")
        })
        return _obj


