# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from cleanlist_ai.models.usage_group_row import UsageGroupRow
from typing import Optional, Set
from typing_extensions import Self

class UsageReportResponse(BaseModel):
    """
    UsageReportResponse
    """ # noqa: E501
    days: StrictInt = Field(description="Length of the reporting window in days (as requested).")
    group_by: StrictStr = Field(description="Dimension the rows are grouped by: `tool`, `key`, `day`, or `error`.")
    total_calls: StrictInt = Field(description="Total API calls across all buckets in the window.")
    total_credits_spent: Union[StrictFloat, StrictInt] = Field(description="Total credits spent across all buckets. Currently 0.0 until the request log gains a per-row cost column.")
    total_errors: StrictInt = Field(description="Total error (non-2xx) responses across all buckets.")
    rows: List[UsageGroupRow] = Field(description="Per-bucket usage rows for the requested `group_by` dimension.")
    __properties: ClassVar[List[str]] = ["days", "group_by", "total_calls", "total_credits_spent", "total_errors", "rows"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsageReportResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rows (list)
        _items = []
        if self.rows:
            for _item_rows in self.rows:
                if _item_rows:
                    _items.append(_item_rows.to_dict())
            _dict['rows'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsageReportResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "days": obj.get("days"),
            "group_by": obj.get("group_by"),
            "total_calls": obj.get("total_calls"),
            "total_credits_spent": obj.get("total_credits_spent"),
            "total_errors": obj.get("total_errors"),
            "rows": [UsageGroupRow.from_dict(_item) for _item in obj["rows"]] if obj.get("rows") is not None else None
        })
        return _obj


