# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cleanlist_ai.models.single_enrichment_result_read import SingleEnrichmentResultRead
from typing import Optional, Set
from typing_extensions import Self

class WorkflowStatusResponse(BaseModel):
    """
    WorkflowStatusResponse
    """ # noqa: E501
    task_id: Optional[StrictStr] = None
    timestamp_ms: Optional[StrictInt] = None
    agent_instructions: Optional[StrictStr] = None
    usage: Optional[StrictStr] = None
    message: Optional[StrictStr] = None
    workflow_id: StrictStr = Field(description="The workflow (or cohort task) handle being polled.")
    status: StrictStr = Field(description="Outer workflow status: e.g. 'pending', 'running', 'completed', 'failed', 'cancelled'.")
    progress: Optional[StrictInt] = None
    total: Optional[StrictInt] = None
    processed: Optional[StrictInt] = None
    completed: Optional[StrictInt] = None
    failed: Optional[StrictInt] = None
    enrichment_type: Optional[StrictStr] = None
    lead_list_id: Optional[StrictStr] = None
    summary: Optional[Dict[str, Any]] = None
    refund_status: Optional[StrictStr] = None
    refund_message: Optional[StrictStr] = None
    result: Optional[SingleEnrichmentResultRead] = None
    credits_charged: Optional[StrictInt] = None
    credits_refunded: Optional[StrictInt] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["task_id", "timestamp_ms", "agent_instructions", "usage", "message", "workflow_id", "status", "progress", "total", "processed", "completed", "failed", "enrichment_type", "lead_list_id", "summary", "refund_status", "refund_message", "result", "credits_charged", "credits_refunded"]

    @field_validator('refund_status')
    def refund_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['not_applicable', 'pending_review']):
            raise ValueError("must be one of enum values ('not_applicable', 'pending_review')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of result
        if self.result:
            _dict['result'] = self.result.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict['task_id'] = None

        # set to None if timestamp_ms (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_ms is None and "timestamp_ms" in self.model_fields_set:
            _dict['timestamp_ms'] = None

        # set to None if agent_instructions (nullable) is None
        # and model_fields_set contains the field
        if self.agent_instructions is None and "agent_instructions" in self.model_fields_set:
            _dict['agent_instructions'] = None

        # set to None if usage (nullable) is None
        # and model_fields_set contains the field
        if self.usage is None and "usage" in self.model_fields_set:
            _dict['usage'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if progress (nullable) is None
        # and model_fields_set contains the field
        if self.progress is None and "progress" in self.model_fields_set:
            _dict['progress'] = None

        # set to None if total (nullable) is None
        # and model_fields_set contains the field
        if self.total is None and "total" in self.model_fields_set:
            _dict['total'] = None

        # set to None if processed (nullable) is None
        # and model_fields_set contains the field
        if self.processed is None and "processed" in self.model_fields_set:
            _dict['processed'] = None

        # set to None if completed (nullable) is None
        # and model_fields_set contains the field
        if self.completed is None and "completed" in self.model_fields_set:
            _dict['completed'] = None

        # set to None if failed (nullable) is None
        # and model_fields_set contains the field
        if self.failed is None and "failed" in self.model_fields_set:
            _dict['failed'] = None

        # set to None if enrichment_type (nullable) is None
        # and model_fields_set contains the field
        if self.enrichment_type is None and "enrichment_type" in self.model_fields_set:
            _dict['enrichment_type'] = None

        # set to None if lead_list_id (nullable) is None
        # and model_fields_set contains the field
        if self.lead_list_id is None and "lead_list_id" in self.model_fields_set:
            _dict['lead_list_id'] = None

        # set to None if summary (nullable) is None
        # and model_fields_set contains the field
        if self.summary is None and "summary" in self.model_fields_set:
            _dict['summary'] = None

        # set to None if refund_status (nullable) is None
        # and model_fields_set contains the field
        if self.refund_status is None and "refund_status" in self.model_fields_set:
            _dict['refund_status'] = None

        # set to None if refund_message (nullable) is None
        # and model_fields_set contains the field
        if self.refund_message is None and "refund_message" in self.model_fields_set:
            _dict['refund_message'] = None

        # set to None if result (nullable) is None
        # and model_fields_set contains the field
        if self.result is None and "result" in self.model_fields_set:
            _dict['result'] = None

        # set to None if credits_charged (nullable) is None
        # and model_fields_set contains the field
        if self.credits_charged is None and "credits_charged" in self.model_fields_set:
            _dict['credits_charged'] = None

        # set to None if credits_refunded (nullable) is None
        # and model_fields_set contains the field
        if self.credits_refunded is None and "credits_refunded" in self.model_fields_set:
            _dict['credits_refunded'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_id": obj.get("task_id"),
            "timestamp_ms": obj.get("timestamp_ms"),
            "agent_instructions": obj.get("agent_instructions"),
            "usage": obj.get("usage"),
            "message": obj.get("message"),
            "workflow_id": obj.get("workflow_id"),
            "status": obj.get("status"),
            "progress": obj.get("progress"),
            "total": obj.get("total"),
            "processed": obj.get("processed"),
            "completed": obj.get("completed"),
            "failed": obj.get("failed"),
            "enrichment_type": obj.get("enrichment_type"),
            "lead_list_id": obj.get("lead_list_id"),
            "summary": obj.get("summary"),
            "refund_status": obj.get("refund_status"),
            "refund_message": obj.get("refund_message"),
            "result": SingleEnrichmentResultRead.from_dict(obj["result"]) if obj.get("result") is not None else None,
            "credits_charged": obj.get("credits_charged"),
            "credits_refunded": obj.get("credits_refunded")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


