# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class AddLeadsResponse(BaseModel):
    """
    AddLeadsResponse
    """ # noqa: E501
    list_id: StrictStr = Field(description="Identifier of the list leads were added to.")
    added: StrictInt = Field(description="Number of leads newly inserted into the list (billed rows).")
    skipped_duplicates: StrictInt = Field(description="Leads already in the list that were skipped (not re-billed).")
    created: Optional[StrictInt] = None
    credits_charged: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, description="Import credits charged. Import is free, so this is 0; only enrichment is billed (separately).")
    __properties: ClassVar[List[str]] = ["list_id", "added", "skipped_duplicates", "created", "credits_charged"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddLeadsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if created (nullable) is None
        # and model_fields_set contains the field
        if self.created is None and "created" in self.model_fields_set:
            _dict['created'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddLeadsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "list_id": obj.get("list_id"),
            "added": obj.get("added"),
            "skipped_duplicates": obj.get("skipped_duplicates"),
            "created": obj.get("created"),
            "credits_charged": obj.get("credits_charged") if obj.get("credits_charged") is not None else 0
        })
        return _obj


