# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CompanyRecord(BaseModel):
    """
    Synchronous company enrichment result. Shape follows what CompanyDB returns, but with stable field names independent of Crustdata's response shape drift.
    """ # noqa: E501
    company_id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    domain: Optional[StrictStr] = None
    industry: Optional[StrictStr] = None
    industries: Optional[List[StrictStr]] = None
    employee_count: Optional[StrictInt] = None
    employee_count_range: Optional[StrictStr] = None
    revenue_range: Optional[StrictStr] = None
    hq_location: Optional[StrictStr] = None
    funding_stage: Optional[StrictStr] = None
    total_funding_usd: Optional[StrictInt] = None
    tech_stack: Optional[List[StrictStr]] = None
    linkedin_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["company_id", "name", "domain", "industry", "industries", "employee_count", "employee_count_range", "revenue_range", "hq_location", "funding_stage", "total_funding_usd", "tech_stack", "linkedin_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompanyRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if company_id (nullable) is None
        # and model_fields_set contains the field
        if self.company_id is None and "company_id" in self.model_fields_set:
            _dict['company_id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if domain (nullable) is None
        # and model_fields_set contains the field
        if self.domain is None and "domain" in self.model_fields_set:
            _dict['domain'] = None

        # set to None if industry (nullable) is None
        # and model_fields_set contains the field
        if self.industry is None and "industry" in self.model_fields_set:
            _dict['industry'] = None

        # set to None if industries (nullable) is None
        # and model_fields_set contains the field
        if self.industries is None and "industries" in self.model_fields_set:
            _dict['industries'] = None

        # set to None if employee_count (nullable) is None
        # and model_fields_set contains the field
        if self.employee_count is None and "employee_count" in self.model_fields_set:
            _dict['employee_count'] = None

        # set to None if employee_count_range (nullable) is None
        # and model_fields_set contains the field
        if self.employee_count_range is None and "employee_count_range" in self.model_fields_set:
            _dict['employee_count_range'] = None

        # set to None if revenue_range (nullable) is None
        # and model_fields_set contains the field
        if self.revenue_range is None and "revenue_range" in self.model_fields_set:
            _dict['revenue_range'] = None

        # set to None if hq_location (nullable) is None
        # and model_fields_set contains the field
        if self.hq_location is None and "hq_location" in self.model_fields_set:
            _dict['hq_location'] = None

        # set to None if funding_stage (nullable) is None
        # and model_fields_set contains the field
        if self.funding_stage is None and "funding_stage" in self.model_fields_set:
            _dict['funding_stage'] = None

        # set to None if total_funding_usd (nullable) is None
        # and model_fields_set contains the field
        if self.total_funding_usd is None and "total_funding_usd" in self.model_fields_set:
            _dict['total_funding_usd'] = None

        # set to None if tech_stack (nullable) is None
        # and model_fields_set contains the field
        if self.tech_stack is None and "tech_stack" in self.model_fields_set:
            _dict['tech_stack'] = None

        # set to None if linkedin_url (nullable) is None
        # and model_fields_set contains the field
        if self.linkedin_url is None and "linkedin_url" in self.model_fields_set:
            _dict['linkedin_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompanyRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "company_id": obj.get("company_id"),
            "name": obj.get("name"),
            "domain": obj.get("domain"),
            "industry": obj.get("industry"),
            "industries": obj.get("industries"),
            "employee_count": obj.get("employee_count"),
            "employee_count_range": obj.get("employee_count_range"),
            "revenue_range": obj.get("revenue_range"),
            "hq_location": obj.get("hq_location"),
            "funding_stage": obj.get("funding_stage"),
            "total_funding_usd": obj.get("total_funding_usd"),
            "tech_stack": obj.get("tech_stack"),
            "linkedin_url": obj.get("linkedin_url")
        })
        return _obj


