# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class EnrichByTaskRequest(BaseModel):
    """
    EnrichByTaskRequest
    """ # noqa: E501
    task_id: StrictStr = Field(description="Task handle from a prior search_people / search_companies / list_leads_in_list call. Org-scoped and time-limited; re-run the search to refresh an expired handle.")
    data_points: Annotated[List[StrictStr], Field(min_length=1)] = Field(description="Fields to enrich. Person tasks accept Email, Phone, LinkedIn; company tasks accept Industry, Employees, Revenue, Funding, TechStack, Domain. Must match the task's entity type. For person cohorts, Email+Phone → 'full', Phone → 'phone_only', else 'partial'.")
    entity_ids: Optional[List[StrictStr]] = None
    lead_list_id: Optional[StrictStr] = None
    quote_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["task_id", "data_points", "entity_ids", "lead_list_id", "quote_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnrichByTaskRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if entity_ids (nullable) is None
        # and model_fields_set contains the field
        if self.entity_ids is None and "entity_ids" in self.model_fields_set:
            _dict['entity_ids'] = None

        # set to None if lead_list_id (nullable) is None
        # and model_fields_set contains the field
        if self.lead_list_id is None and "lead_list_id" in self.model_fields_set:
            _dict['lead_list_id'] = None

        # set to None if quote_id (nullable) is None
        # and model_fields_set contains the field
        if self.quote_id is None and "quote_id" in self.model_fields_set:
            _dict['quote_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnrichByTaskRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_id": obj.get("task_id"),
            "data_points": obj.get("data_points"),
            "entity_ids": obj.get("entity_ids"),
            "lead_list_id": obj.get("lead_list_id"),
            "quote_id": obj.get("quote_id")
        })
        return _obj


