# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EnrichPersonRequest(BaseModel):
    """
    EnrichPersonRequest
    """ # noqa: E501
    lead_list_id: StrictStr = Field(description="ID of the lead list the enriched contact is written to when the workflow completes. Must be a list your API key can access.")
    email: Optional[StrictStr] = None
    linkedin_url: Optional[StrictStr] = None
    phone: Optional[StrictStr] = None
    first_name: Optional[StrictStr] = None
    last_name: Optional[StrictStr] = None
    company_name: Optional[StrictStr] = None
    domain: Optional[StrictStr] = None
    person_id: Optional[StrictStr] = None
    enrichment_type: Optional[StrictStr] = None
    include_phone: Optional[StrictBool] = Field(default=False, description="Legacy scope toggle, kept for back-compat. false → 'partial', true → 'phone_only'. Ignored when enrichment_type is set.")
    quote_id: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["lead_list_id", "email", "linkedin_url", "phone", "first_name", "last_name", "company_name", "domain", "person_id", "enrichment_type", "include_phone", "quote_id"]

    @field_validator('enrichment_type')
    def enrichment_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['partial', 'phone_only', 'full']):
            raise ValueError("must be one of enum values ('partial', 'phone_only', 'full')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnrichPersonRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if linkedin_url (nullable) is None
        # and model_fields_set contains the field
        if self.linkedin_url is None and "linkedin_url" in self.model_fields_set:
            _dict['linkedin_url'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        # set to None if first_name (nullable) is None
        # and model_fields_set contains the field
        if self.first_name is None and "first_name" in self.model_fields_set:
            _dict['first_name'] = None

        # set to None if last_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_name is None and "last_name" in self.model_fields_set:
            _dict['last_name'] = None

        # set to None if company_name (nullable) is None
        # and model_fields_set contains the field
        if self.company_name is None and "company_name" in self.model_fields_set:
            _dict['company_name'] = None

        # set to None if domain (nullable) is None
        # and model_fields_set contains the field
        if self.domain is None and "domain" in self.model_fields_set:
            _dict['domain'] = None

        # set to None if person_id (nullable) is None
        # and model_fields_set contains the field
        if self.person_id is None and "person_id" in self.model_fields_set:
            _dict['person_id'] = None

        # set to None if enrichment_type (nullable) is None
        # and model_fields_set contains the field
        if self.enrichment_type is None and "enrichment_type" in self.model_fields_set:
            _dict['enrichment_type'] = None

        # set to None if quote_id (nullable) is None
        # and model_fields_set contains the field
        if self.quote_id is None and "quote_id" in self.model_fields_set:
            _dict['quote_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnrichPersonRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lead_list_id": obj.get("lead_list_id"),
            "email": obj.get("email"),
            "linkedin_url": obj.get("linkedin_url"),
            "phone": obj.get("phone"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "company_name": obj.get("company_name"),
            "domain": obj.get("domain"),
            "person_id": obj.get("person_id"),
            "enrichment_type": obj.get("enrichment_type"),
            "include_phone": obj.get("include_phone") if obj.get("include_phone") is not None else False,
            "quote_id": obj.get("quote_id")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


