# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EnrichPersonResponse(BaseModel):
    """
    EnrichPersonResponse
    """ # noqa: E501
    task_id: Optional[StrictStr] = None
    timestamp_ms: Optional[StrictInt] = None
    agent_instructions: Optional[StrictStr] = None
    usage: Optional[StrictStr] = None
    message: Optional[StrictStr] = None
    workflow_id: StrictStr = Field(description="Handle for the async enrichment workflow. Poll it via poll_url.")
    status: StrictStr = Field(description="Always 'pending' on dispatch — the workflow runs asynchronously.")
    credits_reserved: StrictInt = Field(description="Upfront credit reservation cap (1/10/11 for partial/phone_only/full). Pay-for-results: the workflow refunds the unused portion at settle, so the final debit may be lower. Poll status for the actual charge.")
    lead_list_id: StrictStr = Field(description="List the enriched contact will be written to on completion.")
    poll_url: StrictStr = Field(description="Fully-qualified URL to poll for workflow status and results.")
    __properties: ClassVar[List[str]] = ["task_id", "timestamp_ms", "agent_instructions", "usage", "message", "workflow_id", "status", "credits_reserved", "lead_list_id", "poll_url"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending']):
            raise ValueError("must be one of enum values ('pending')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnrichPersonResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict['task_id'] = None

        # set to None if timestamp_ms (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_ms is None and "timestamp_ms" in self.model_fields_set:
            _dict['timestamp_ms'] = None

        # set to None if agent_instructions (nullable) is None
        # and model_fields_set contains the field
        if self.agent_instructions is None and "agent_instructions" in self.model_fields_set:
            _dict['agent_instructions'] = None

        # set to None if usage (nullable) is None
        # and model_fields_set contains the field
        if self.usage is None and "usage" in self.model_fields_set:
            _dict['usage'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnrichPersonResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_id": obj.get("task_id"),
            "timestamp_ms": obj.get("timestamp_ms"),
            "agent_instructions": obj.get("agent_instructions"),
            "usage": obj.get("usage"),
            "message": obj.get("message"),
            "workflow_id": obj.get("workflow_id"),
            "status": obj.get("status"),
            "credits_reserved": obj.get("credits_reserved"),
            "lead_list_id": obj.get("lead_list_id"),
            "poll_url": obj.get("poll_url")
        })
        return _obj


