# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EstimateCostRequest(BaseModel):
    """
    EstimateCostRequest
    """ # noqa: E501
    tool: StrictStr = Field(description="Tool to price. Must be a key in the server's cost table (e.g. `enrich_list`, `enrich_person`, `run_smart_agent`, `sync_to_crm`, `add_person_enrichments`). Unknown tools return a 400.")
    list_id: Optional[StrictStr] = None
    filters: Optional[Dict[str, Any]] = None
    row_count: Optional[StrictInt] = None
    scope: Optional[StrictStr] = None
    agent_type: Optional[StrictStr] = None
    include_phone: Optional[StrictBool] = Field(default=False, description="Legacy boolean that requests phone enrichment when `enrichment_type`/`scope` are not set. Kept for back-compat; prefer `scope`/`enrichment_type`.")
    provider: Optional[StrictStr] = None
    sub_action: Optional[StrictStr] = None
    enrichment_type: Optional[StrictStr] = None
    task_id: Optional[StrictStr] = None
    data_points: Optional[List[StrictStr]] = None
    entity_ids: Optional[List[StrictStr]] = None
    extra: Optional[Dict[str, Any]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["tool", "list_id", "filters", "row_count", "scope", "agent_type", "include_phone", "provider", "sub_action", "enrichment_type", "task_id", "data_points", "entity_ids", "extra"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EstimateCostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if list_id (nullable) is None
        # and model_fields_set contains the field
        if self.list_id is None and "list_id" in self.model_fields_set:
            _dict['list_id'] = None

        # set to None if filters (nullable) is None
        # and model_fields_set contains the field
        if self.filters is None and "filters" in self.model_fields_set:
            _dict['filters'] = None

        # set to None if row_count (nullable) is None
        # and model_fields_set contains the field
        if self.row_count is None and "row_count" in self.model_fields_set:
            _dict['row_count'] = None

        # set to None if scope (nullable) is None
        # and model_fields_set contains the field
        if self.scope is None and "scope" in self.model_fields_set:
            _dict['scope'] = None

        # set to None if agent_type (nullable) is None
        # and model_fields_set contains the field
        if self.agent_type is None and "agent_type" in self.model_fields_set:
            _dict['agent_type'] = None

        # set to None if provider (nullable) is None
        # and model_fields_set contains the field
        if self.provider is None and "provider" in self.model_fields_set:
            _dict['provider'] = None

        # set to None if sub_action (nullable) is None
        # and model_fields_set contains the field
        if self.sub_action is None and "sub_action" in self.model_fields_set:
            _dict['sub_action'] = None

        # set to None if enrichment_type (nullable) is None
        # and model_fields_set contains the field
        if self.enrichment_type is None and "enrichment_type" in self.model_fields_set:
            _dict['enrichment_type'] = None

        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict['task_id'] = None

        # set to None if data_points (nullable) is None
        # and model_fields_set contains the field
        if self.data_points is None and "data_points" in self.model_fields_set:
            _dict['data_points'] = None

        # set to None if entity_ids (nullable) is None
        # and model_fields_set contains the field
        if self.entity_ids is None and "entity_ids" in self.model_fields_set:
            _dict['entity_ids'] = None

        # set to None if extra (nullable) is None
        # and model_fields_set contains the field
        if self.extra is None and "extra" in self.model_fields_set:
            _dict['extra'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EstimateCostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tool": obj.get("tool"),
            "list_id": obj.get("list_id"),
            "filters": obj.get("filters"),
            "row_count": obj.get("row_count"),
            "scope": obj.get("scope"),
            "agent_type": obj.get("agent_type"),
            "include_phone": obj.get("include_phone") if obj.get("include_phone") is not None else False,
            "provider": obj.get("provider"),
            "sub_action": obj.get("sub_action"),
            "enrichment_type": obj.get("enrichment_type"),
            "task_id": obj.get("task_id"),
            "data_points": obj.get("data_points"),
            "entity_ids": obj.get("entity_ids"),
            "extra": obj.get("extra")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


