# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ListDetailResponse(BaseModel):
    """
    ListDetailResponse
    """ # noqa: E501
    task_id: Optional[StrictStr] = None
    timestamp_ms: Optional[StrictInt] = None
    agent_instructions: Optional[StrictStr] = None
    usage: Optional[StrictStr] = None
    message: Optional[StrictStr] = None
    list_id: StrictStr = Field(description="Stable identifier of the list.")
    name: StrictStr = Field(description="Display name of the list.")
    description: Optional[StrictStr] = None
    lead_count: StrictInt = Field(description="Live count of leads in the list (derived from a fresh COUNT).")
    enriched_count: StrictInt = Field(description="How many of the leads have been enriched (email/phone found).")
    folder_id: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = None
    reused: Optional[StrictBool] = Field(default=False, description="True only when POST /lead-lists returned a pre-existing same-name list (idempotent reuse). Always false on reads and genuine creates.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["task_id", "timestamp_ms", "agent_instructions", "usage", "message", "list_id", "name", "description", "lead_count", "enriched_count", "folder_id", "created_at", "reused"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListDetailResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict['task_id'] = None

        # set to None if timestamp_ms (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_ms is None and "timestamp_ms" in self.model_fields_set:
            _dict['timestamp_ms'] = None

        # set to None if agent_instructions (nullable) is None
        # and model_fields_set contains the field
        if self.agent_instructions is None and "agent_instructions" in self.model_fields_set:
            _dict['agent_instructions'] = None

        # set to None if usage (nullable) is None
        # and model_fields_set contains the field
        if self.usage is None and "usage" in self.model_fields_set:
            _dict['usage'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if folder_id (nullable) is None
        # and model_fields_set contains the field
        if self.folder_id is None and "folder_id" in self.model_fields_set:
            _dict['folder_id'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListDetailResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_id": obj.get("task_id"),
            "timestamp_ms": obj.get("timestamp_ms"),
            "agent_instructions": obj.get("agent_instructions"),
            "usage": obj.get("usage"),
            "message": obj.get("message"),
            "list_id": obj.get("list_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "lead_count": obj.get("lead_count"),
            "enriched_count": obj.get("enriched_count"),
            "folder_id": obj.get("folder_id"),
            "created_at": obj.get("created_at"),
            "reused": obj.get("reused") if obj.get("reused") is not None else False
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


