# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class RunSmartAgentRequest(BaseModel):
    """
    RunSmartAgentRequest
    """ # noqa: E501
    list_id: StrictStr = Field(description="UUID of the lead list the agent runs against. Must be a list this API key can access (owned, org-visible, or shared) — a known id for a private list in the same org is rejected with 404.")
    agent_type: Optional[StrictStr] = Field(default='custom_ai', description="Which agent to run. `custom_ai` runs your own `prompt`; `cold_intro_email` drafts a personalized opener from an email template. The preset research agents (`title_normalizer`, `company_intel`, `pain_point_hypothesis`) run a baked-in instruction and ignore `prompt`. All types execute asynchronously as an AI smart column.")
    prompt: Optional[StrictStr] = None
    column_name: Annotated[str, Field(min_length=1, strict=True, max_length=100)] = Field(description="Display name for the new column that stores each lead's agent output. Re-using an existing column name appends to it unless `overwrite=true` is set.")
    lead_scope: Optional[StrictStr] = Field(default='subset', description="`subset` runs on up to `max_rows` leads (the fast, cheap path). `all` runs on the entire list, but any `all` run above the configured threshold (default 500 leads) is blocked with a 400 `approval_required` until you narrow scope or route a human approval.")
    max_rows: Optional[Annotated[int, Field(le=10000, strict=True, ge=1)]] = Field(default=100, description="Upper bound on how many leads to process when `lead_scope='subset'`. Clamped to the list size. Ignored when `lead_scope='all'`.")
    quote_id: StrictStr = Field(description="Single-use spend quote from POST /credits/estimate, signed for this exact request shape (list_id + agent_type + column_name + row count). It is verified and atomically redeemed before the run starts; a stale, mismatched, or already-used quote returns a 400 or 409. Re-quote if you change any field.")
    overwrite: Optional[StrictBool] = Field(default=False, description="When true, existing values in a column of the same name are overwritten instead of preserved. Passed through to the workflow via column metadata.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["list_id", "agent_type", "prompt", "column_name", "lead_scope", "max_rows", "quote_id", "overwrite"]

    @field_validator('agent_type')
    def agent_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['custom_ai', 'cold_intro_email', 'title_normalizer', 'company_intel', 'pain_point_hypothesis']):
            raise ValueError("must be one of enum values ('custom_ai', 'cold_intro_email', 'title_normalizer', 'company_intel', 'pain_point_hypothesis')")
        return value

    @field_validator('lead_scope')
    def lead_scope_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['subset', 'all']):
            raise ValueError("must be one of enum values ('subset', 'all')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RunSmartAgentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if prompt (nullable) is None
        # and model_fields_set contains the field
        if self.prompt is None and "prompt" in self.model_fields_set:
            _dict['prompt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RunSmartAgentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "list_id": obj.get("list_id"),
            "agent_type": obj.get("agent_type") if obj.get("agent_type") is not None else 'custom_ai',
            "prompt": obj.get("prompt"),
            "column_name": obj.get("column_name"),
            "lead_scope": obj.get("lead_scope") if obj.get("lead_scope") is not None else 'subset',
            "max_rows": obj.get("max_rows") if obj.get("max_rows") is not None else 100,
            "quote_id": obj.get("quote_id"),
            "overwrite": obj.get("overwrite") if obj.get("overwrite") is not None else False
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


