# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RunSmartAgentResponse(BaseModel):
    """
    Three identifiers can live on this response (T1-6 ID-space rename):  - `smart_agent_task_id` — canonical id for polling   `get_smart_agent_results`. - `smart_agent_task_ids` — dict keyed by column type when   `process_smart_columns` returns multiple underlying task ids. - `task_id` (from EnvelopeFields) — kept populated for back-compat   with v1.0 callers that read it from the envelope.  The three are distinct identifiers. A smart-column run's id is NOT an MCP cohort handle, but the envelope still carries `task_id` for transitional compat. New callers should read `smart_agent_task_id`.
    """ # noqa: E501
    task_id: Optional[StrictStr] = None
    timestamp_ms: Optional[StrictInt] = None
    agent_instructions: Optional[StrictStr] = None
    usage: Optional[StrictStr] = None
    message: Optional[StrictStr] = None
    smart_agent_task_id: StrictStr = Field(description="Canonical run id. Pass this to GET /smart-agents/{id} to poll progress and per-lead results.")
    smart_agent_task_ids: Optional[Dict[str, StrictStr]] = Field(default=None, description="Underlying task ids keyed by column type. Usually a single entry; populated when the run fans out to more than one smart-column task.")
    status: StrictStr = Field(description="Initial run status; always 'pending' at launch.")
    list_id: StrictStr = Field(description="UUID of the lead list the run was launched against.")
    column_name: StrictStr = Field(description="Name of the column that will hold each lead's output.")
    estimated_cost: StrictInt = Field(description="Credits expected for this run (per-lead rate × row count). Actual debit happens as rows complete and may be lower if leads fail.")
    __properties: ClassVar[List[str]] = ["task_id", "timestamp_ms", "agent_instructions", "usage", "message", "smart_agent_task_id", "smart_agent_task_ids", "status", "list_id", "column_name", "estimated_cost"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RunSmartAgentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict['task_id'] = None

        # set to None if timestamp_ms (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_ms is None and "timestamp_ms" in self.model_fields_set:
            _dict['timestamp_ms'] = None

        # set to None if agent_instructions (nullable) is None
        # and model_fields_set contains the field
        if self.agent_instructions is None and "agent_instructions" in self.model_fields_set:
            _dict['agent_instructions'] = None

        # set to None if usage (nullable) is None
        # and model_fields_set contains the field
        if self.usage is None and "usage" in self.model_fields_set:
            _dict['usage'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RunSmartAgentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_id": obj.get("task_id"),
            "timestamp_ms": obj.get("timestamp_ms"),
            "agent_instructions": obj.get("agent_instructions"),
            "usage": obj.get("usage"),
            "message": obj.get("message"),
            "smart_agent_task_id": obj.get("smart_agent_task_id"),
            "smart_agent_task_ids": obj.get("smart_agent_task_ids"),
            "status": obj.get("status"),
            "list_id": obj.get("list_id"),
            "column_name": obj.get("column_name"),
            "estimated_cost": obj.get("estimated_cost")
        })
        return _obj


