# coding: utf-8

"""
    Cleanlist API (v2)

    Versioned public API surface (v2) for the Cleanlist MCP and direct API consumers: workspace, lead lists, enrichment, smart agents, sync, and export.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WhoamiResponse(BaseModel):
    """
    WhoamiResponse
    """ # noqa: E501
    task_id: Optional[StrictStr] = None
    timestamp_ms: Optional[StrictInt] = None
    agent_instructions: Optional[StrictStr] = None
    usage: Optional[StrictStr] = None
    message: Optional[StrictStr] = None
    user_email: Optional[StrictStr]
    user_id: Optional[StrictStr] = None
    user_name: Optional[StrictStr] = None
    organization_id: StrictStr = Field(description="Cleanlist organization id that owns this session's credits and lists.")
    organization_name: Optional[StrictStr] = None
    auth_type: StrictStr = Field(description="How the caller authenticated: `clerk_jwt` (portal session token), `api_key` (a `clapi_` bearer key), or `oauth` (third-party grant).")
    scopes: List[Optional[StrictStr]] = Field(description="Granted permission scopes for this credential (per-user Clerk `publicMetadata.cleanlist_scopes`). Endpoints gate on these — e.g. `credits:read`, `search:read`, `lists:write`, `enrichment:write`, `admin:api_keys`.")
    tier: StrictStr = Field(description="Resolved plan tier from the org's Stripe `credits_product_id` (V2 'Scale' buyers map to `enterprise`). The MCP reads this once per session to tier-filter its advertised tool list. Unknown / unmapped products fall through to `free` (the safe default).")
    appsumo_tier: Optional[StrictInt] = None
    features: List[Optional[StrictStr]] = Field(description="EFFECTIVE feature grants the gates actually enforce: base Stripe tier ∪ AppSumo carve-outs − AppSumo blocks (via `has_feature_effective`). Sourced from the same function the server-side gate uses so the advertised list and the gate can't drift. Sorted alphabetically for stable diffs.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["task_id", "timestamp_ms", "agent_instructions", "usage", "message", "user_email", "user_id", "user_name", "organization_id", "organization_name", "auth_type", "scopes", "tier", "appsumo_tier", "features"]

    @field_validator('auth_type')
    def auth_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['clerk_jwt', 'api_key', 'oauth']):
            raise ValueError("must be one of enum values ('clerk_jwt', 'api_key', 'oauth')")
        return value

    @field_validator('tier')
    def tier_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['free', 'starter', 'pro', 'enterprise']):
            raise ValueError("must be one of enum values ('free', 'starter', 'pro', 'enterprise')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WhoamiResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict['task_id'] = None

        # set to None if timestamp_ms (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_ms is None and "timestamp_ms" in self.model_fields_set:
            _dict['timestamp_ms'] = None

        # set to None if agent_instructions (nullable) is None
        # and model_fields_set contains the field
        if self.agent_instructions is None and "agent_instructions" in self.model_fields_set:
            _dict['agent_instructions'] = None

        # set to None if usage (nullable) is None
        # and model_fields_set contains the field
        if self.usage is None and "usage" in self.model_fields_set:
            _dict['usage'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if user_email (nullable) is None
        # and model_fields_set contains the field
        if self.user_email is None and "user_email" in self.model_fields_set:
            _dict['user_email'] = None

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['user_id'] = None

        # set to None if user_name (nullable) is None
        # and model_fields_set contains the field
        if self.user_name is None and "user_name" in self.model_fields_set:
            _dict['user_name'] = None

        # set to None if organization_name (nullable) is None
        # and model_fields_set contains the field
        if self.organization_name is None and "organization_name" in self.model_fields_set:
            _dict['organization_name'] = None

        # set to None if appsumo_tier (nullable) is None
        # and model_fields_set contains the field
        if self.appsumo_tier is None and "appsumo_tier" in self.model_fields_set:
            _dict['appsumo_tier'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WhoamiResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_id": obj.get("task_id"),
            "timestamp_ms": obj.get("timestamp_ms"),
            "agent_instructions": obj.get("agent_instructions"),
            "usage": obj.get("usage"),
            "message": obj.get("message"),
            "user_email": obj.get("user_email"),
            "user_id": obj.get("user_id"),
            "user_name": obj.get("user_name"),
            "organization_id": obj.get("organization_id"),
            "organization_name": obj.get("organization_name"),
            "auth_type": obj.get("auth_type"),
            "scopes": obj.get("scopes"),
            "tier": obj.get("tier"),
            "appsumo_tier": obj.get("appsumo_tier"),
            "features": obj.get("features")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


